In [1]:
import pandas as pd

In [12]:
import numpy as np

In [3]:
k=[4,7,2,9,7,3,90,50]
k

[4, 7, 2, 9, 7, 3, 90, 50]

In [18]:
t=np.array(k)
t

array([[ 4,  7],
       [ 2,  9],
       [ 7,  3],
       [90, 50]])

In [19]:
t.ndim

2

In [21]:
pd.Series()


ValueError: Data must be 1-dimensional, got ndarray of shape (4, 2) instead

In [22]:
t

array([[ 4,  7],
       [ 2,  9],
       [ 7,  3],
       [90, 50]])

In [8]:
k=[[4,7],[2,9],[7,3],[90,50]]
k

[[4, 7], [2, 9], [7, 3], [90, 50]]

In [14]:
np.array(k)

array([[ 4,  7],
       [ 2,  9],
       [ 7,  3],
       [90, 50]])

In [25]:
pd.Series(k)

0      [4, 7]
1      [2, 9]
2      [7, 3]
3    [90, 50]
dtype: object

In [23]:
pd.DataFrame(t)

0   1
0   4   7
1   2   9
2   7   3
3  90  50

In [29]:
pd.DataFrame(k,columns=['name','sub'],index=[289,290,291,292])
pd

<module 'pandas' from 'C:\\Users\\neses\\New folder\\New folder\\anaconda\\Lib\\site-packages\\pandas\\__init__.py'>