In [2]:
import numpy as np

In [3]:
np.random.randint(18,21,200)

array([19, 20, 18, 20, 19, 20, 20, 19, 19, 19, 20, 18, 18, 19, 18, 20, 20,
       19, 19, 19, 20, 20, 20, 20, 19, 20, 20, 20, 19, 20, 19, 18, 20, 20,
       20, 18, 20, 19, 20, 19, 18, 19, 18, 20, 19, 19, 18, 18, 19, 20, 18,
       18, 19, 18, 19, 20, 18, 19, 18, 19, 20, 19, 20, 18, 20, 19, 18, 18,
       20, 18, 18, 19, 19, 19, 20, 19, 18, 18, 18, 19, 20, 18, 18, 18, 18,
       19, 20, 18, 20, 20, 20, 20, 18, 18, 20, 19, 20, 20, 20, 19, 20, 18,
       19, 18, 18, 18, 18, 18, 18, 19, 18, 18, 18, 18, 19, 19, 18, 18, 20,
       19, 20, 19, 19, 19, 20, 18, 18, 20, 20, 19, 20, 20, 18, 18, 18, 18,
       19, 19, 19, 19, 20, 18, 20, 19, 18, 19, 18, 20, 18, 20, 19, 20, 18,
       19, 18, 18, 20, 19, 18, 20, 20, 19, 19, 19, 20, 19, 20, 20, 20, 19,
       20, 19, 19, 20, 20, 20, 19, 20, 18, 20, 19, 18, 18, 20, 18, 19, 20,
       19, 20, 20, 19, 20, 19, 19, 18, 19, 18, 20, 18, 19])

In [4]:
h=[30,20,5,8,9]
h

[30, 20, 5, 8, 9]

In [5]:
s=(6,2,3,9,7,5,8)
s

(6, 2, 3, 9, 7, 5, 8)

In [6]:
tuple(x**2 for x in s)

(36, 4, 9, 81, 49, 25, 64)

In [7]:
y=list(s)
k=[]
for i in y:
    k.append(i**2)
    s=tuple(k)
    s

In [8]:
s

(36, 4, 9, 81, 49, 25, 64)

In [9]:
m=[]
for i in s:
    if i>30:
        m.append(i)

In [10]:
m

[36, 81, 49, 64]

In [11]:
arr=np.array([20,50,30,70,80,40,36,54,23,98])

In [12]:
arr

array([20, 50, 30, 70, 80, 40, 36, 54, 23, 98])

In [13]:
arr+5

array([ 25,  55,  35,  75,  85,  45,  41,  59,  28, 103])

In [14]:
arr**2

array([ 400, 2500,  900, 4900, 6400, 1600, 1296, 2916,  529, 9604])